openapi: 3.0.3
info:
  title: IP Lookup - Assignment
  description: |-
    This is a simple API which purpose is to provide the country name associated
      with an IP address. The server exposes a lookup endpoint that rely on multiple vendors to provide
      the location of an IP.

      Requirements & Capabilities:

      * **Given an IP address, return the associated country name**

      * **Support multiple vendors** (ex.: https://ipstack.com/)

      * **Naive cache for IP addresses previously requested**

      * **Global configurable rate limits of the server per vendor per hour**

      _If the rate limit of one vendor has exceeded, the API fallback to other vendor(s). If the result is not in cache
      and the rate limit is exceeded for all vendors, it returns an error message._
  contact:
    email: danielgomesnegri@gmail.com
  license:
    name: AGPL-3.0 license
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /:
    get:
      tags:
        - ip
      summary: Lookup an IP address
      description: Returns a the country name
      operationId: lookup
      parameters:
        - name: ip
          in: query
          description: ID to lookup
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lookup'
        '400':
          description: Invalid IP address
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'

        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TooManyRequestsError'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

components:
  schemas:
    Lookup:
      type: object
      properties:
        country_name:
          type: string
          example: United States

    InternalServerError:
      type: object
      properties:
        message:
          type: string
          example: Internal Server Error
        status_code:
          type: integer
          format: int32
          example: 500

    BadRequestError:
      type: object
      properties:
        message:
          type: string
          example: Bad Request
        status_code:
          type: integer
          format: int32
          example: 400
        details:
          type: object
          nullable: true

    TooManyRequestsError:
      type: object
      properties:
        message:
          type: string
          example: Too Many Request
        status_code:
          type: integer
          format: int32
          example: 429
