name: Docker Build

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build
        run: docker build . --file Dockerfile --tag docker.io/danielnegri/ip-lookup.js:$(git rev-parse --short HEAD)
